swagger: "2.0"
info:
  title: EYEAM Rest API
  description: API to provide services for EYEAM Mobile App
  version: 1.0.0
paths:
  /classifier:
    post:
      x-google-backend:
        address: https://mlclassifier-m4asy2ifmq-uc.a.run.app/classifier
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalName'
          description: Successful response
      description: Returns animal name classified by ml model from provided image in x-form
      operationId: get_classification
      summary: Get animal name from ml classification
  /animal:
    get:
      x-google-backend:
        address: https://cloudsql-m4asy2ifmq-uc.a.run.app/animal
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalDetails'
          description: Successful response
      description: Returns animalk details from mysql database based on animalk name.
      operationId: get_animal_info
      summary: Get animalk details cloud sql
  /logs:
    get:
      x-google-backend:
        address: https://cloudsql-m4asy2ifmq-uc.a.run.app/logs
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalDetails'
          description: Successful response
      description: Returns animalk details from mysql database based on animalk name.
      operationId: get_user_log
      summary: Get animalk details cloud sql
  /test:
    get:
      x-google-backend:
        address: https://us-central1-glossy-chimera-350206.cloudfunctions.net/function-1
      responses:
        "200":
          description: Successful response
      description: Returns species details from mysql database based on species name.
      operationId: test
      summary: Get species details cloud sqlasdf qwe 
definitions:
  animalname:
    title: Animal Name
    description: animal name classified by the ML Model
    type: object
    properties:
      animalName:
        type: string     
  animalDetails:
    title: Root Type for animalDetails
    description: Species details object fetched from cloud sql
    type: object
    properties:
      namailmiah:
        type: string
      namapopuler:
        type: string
      iucn:
        type: string
      deskripsi:
        type: string
      foto:
        type: string
      habitat:
        type: string
      populasi:
        type: string
      conserv:
        type: string
      persebaran:
        type: string
      threats:
        type: string
      kingdom:
        type: string
      phylum:
        type: string
      class:
        type: string
      order:
        type: string
      family:
        type: string
      genus:
        type: string 
securityDefinitions:
  firebase:
    flow: implicit
    authorizationUrl: ''
    scopes: {}
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/glossy-chimera-350206"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "glossy-chimera-350206"
security:
  - firebase: []