swagger: "2.0"
info:
  title: EYEAM API
  description: API to provide services for EYEAM Mobile App
  version: 1.0.0
paths:
  /classifier:
    post:
      x-google-backend:
        address: https://mlclassifier-t7jrwidujq-et.a.run.app/classifier
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalName'
          description: Successful response
      description: API will identify what kind of animal is in the picture and gives back the scientific name of the animal. It will also logs what it identifies to the database.
      operationId: get_classification
      summary: Get animal name from ml classification and logs it to cloud sql
  /animal:
    get:
      x-google-backend:
        address: https://cloudsql-t7jrwidujq-et.a.run.app/animal
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalDetails'
          description: Successful response
      description: Retrieve Information about a specific animal from the cloud sql instance
      operationId: get_animal_info
      summary: Get animal data from database
  /logs:
    get:
      x-google-backend:
        address: https://cloudsql-t7jrwidujq-et.a.run.app/logs
      responses:
        "200":
          schema:
            $ref: '#/definitions/log'
          description: Successful response
      description: Returns logs from cloudsql based on userid.
      operationId: get_user_log
      summary: Get user logs
definitions:
  animalname:
    title: Animal Name
    description: animal name classified by the ML Model
    type: object
    properties:
      animalName:
        type: string     
  animalDetails:
    title: Root Type for animalDetails
    description: Species details object fetched from cloud sql
    type: object
    properties:
      namailmiah:
        type: string
      namapopuler:
        type: string
      iucn:
        type: string
      deskripsi:
        type: string
      foto:
        type: string
      habitat:
        type: string
      populasi:
        type: string
      conserv:
        type: string
      persebaran:
        type: string
      threats:
        type: string
      kingdom:
        type: string
      phylum:
        type: string
      class:
        type: string
      order:
        type: string
      family:
        type: string
      genus:
        type: string 
  log:
    title: User logs
    description: logs about a specific user's interaction with the classifier
    type: object
    properties:
      data:
        type: object  
securityDefinitions:
  firebase:
    flow: implicit
    authorizationUrl: ''
    scopes: {}
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/acoustic-env-352906"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "acoustic-env-352906"
security:
  - firebase: []
