swagger: "2.0"
info:
  title: EYEAM Rest API
  description: API to provide services for EYEAM Mobile App
  version: 1.0.0
paths:
  /classifier:
    post:
      x-google-backend:
        address: https://mlclassifier-m4asy2ifmq-uc.a.run.app/classifier
      responses:
        "200":
          schema:
            $ref: '#/definitions/animalName'
          description: Successful response
      description: Returns animal name classified by ml model from provided image in x-form
      operationId: get_classification
      summary: Get animal name from ml classification
  /species:
    get:
      x-google-backend:
        address: https://cloudsql-m4asy2ifmq-uc.a.run.app/species
      responses:
        "200":
          schema:
            $ref: '#/definitions/speciesDetails'
          description: Successful response
      description: Returns species details from mysql database based on species name.
      operationId: get_species_info
      summary: Get species details cloud sql
definitions:
  animalname:
    title: Animal Name
    description: animal name classified by the ML Model
    type: object
    properties:
      animalName:
        type: string     
  speciesDetails:
    title: Root Type for speciesDetails
    description: Species details object fetched from cloud sql
    type: object
    properties:
      namapopuler:
        type: string
      namailmiah:
        type: string
      foto:
        type: string
      taxonomy:
        type: string
      kingdom:
        type: string
      genus:
        type: string
      class:
        type: string
      ordo:
        type: string
      family:
        type: string
      species:
        type: string
      deskripsi:
        type: string
      persebaran:
        type: string
      habitat:
        type: string
      iucn:
        type: string
      threats:
        type: string
      conserv:
        type: string
      tersedia:
        type: string
      rataumur:
        type: number
      ratapanjang:
        type: number
      ratalebar:
        type: number
      rataberat:
        type: number
securityDefinitions:
  firebase:
    flow: implicit
    authorizationUrl: ''
    scopes: {}
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/glossy-chimera-350206"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "glossy-chimera-350206"
security:
  - firebase: []