steps:
  # loguser - CI/CD
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - loguser-function
    - --region=asia-southeast2
    - --source=./flask-rest-api/loguser-functions/
    - --trigger-topic=loguser-topic
    - --runtime=python39
    - --entry-point=loguser
    - --set-env-vars=_SQL_HOST=$_SQL_HOST,_SQL_USER=$_SQL_USER,_SQL_PASSWORD=$_SQL_PASSWORD,_SQL_DATABASE=$_SQL_DATABASE
  # cloudsql - Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloudsql:$SHORT_SHA'
      - ./flask-rest-api/cloudsql-run/
  # cloudsql - Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/cloudsql:$SHORT_SHA'
  # cloudsql - Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - cloudsql
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloudsql:$SHORT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--set-env-vars'
      - '_SQL_HOST=$_SQL_HOST,_SQL_USER=$_SQL_USER,_SQL_PASSWORD=$_SQL_PASSWORD,_SQL_DATABASE=$_SQL_DATABASE'
    entrypoint: gcloud
  # mlclassifier - Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/mlclassifier:$SHORT_SHA'
      - ./flask-rest-api/mlclassifier-run/
  # mlclassifier - Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/mlclassifier:$SHORT_SHA'
  # cloudsql - Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - mlclassifier
      - '--image'
      - 'gcr.io/$PROJECT_ID/mlclassifier:$SHORT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--set-env-vars'
      - '_PROJECT_ID=$_PROJECT_ID,_TOPIC_ID=$_TOPIC_ID'
    entrypoint: gcloud
images:
  - 'gcr.io/$PROJECT_ID/cloudsql:$SHORT_SHA'
options:
  logging: NONE
timeout: 3600s
